ensemble:
  weights: {}
models:
  toxicity:
    class: ToxicityModel
    args:
      model_path: unitary/toxic-bert
  zero_shot_extremism:
    class: ZeroShotExtremismNLI
    args:
      model_path: facebook/bart-large-mnli
  heuristic_lexicon:
    class: HeuristicLexiconModel
    args: {}
  hatexplain-roberta:
    class: HateXplainModel
    args:
      model_path: models/hatexplain-roberta
  vibe-checker:
    class: VibeCheckerModel
    args: {}

