ensemble: 
  ...

models:
  # ============================
  # Sentiment Model Ensemble
  # ============================
  # Four specialized text classifiers for hate speech detection
  # Each model has different strengths and weighting strategies
  
  # # 1. HateXplain
  # hatexplain:
  #   class: HateXplainModel
  #   args:
  #     model_path: models/hatexplain-roberta-mini
  
  # 2. Toxicity Model - Conservative toxicity detection (reduces false positives)
  toxicity:
    class: ToxicityModel
    args:
      model_path: unitary/toxic-bert

  # 3. Zero-Shot Extremism NLI - Zero-shot model for extremism detection
  zero_shot_extremism:
    class: ZeroShotExtremismNLI
    args:
      model_path: facebook/bart-large-mnli

  # 4. Heuristic Lexicon Model - Rule-based model for hate speech detection
  heuristic_lexicon:
    class: HeuristicLexiconModel
    args: {}

  # ============================
  # Dummy Models (for testing)
  # ============================
  # Uncomment to test ensemble behavior with dummy predictors
  
  # dummy_1:
  #   class: DummyModel
  #   args:
  #     seed: 0
  
  # dummy_2:
  #   class: DummyModel
  #   args:
  #     seed: 42
